import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsArray, IsNotEmpty, IsNumber, IsOptional, IsString, ValidateNested } from 'class-validator';
import { Type } from 'class-transformer';
import { CreateListingDto } from './create-listing.dto';

export class OfflineListingEntry extends CreateListingDto {
  @ApiPropertyOptional({
    description: 'Temporary UUID generated by the client offline to correlate with offline orders',
    example: 'offline-listing-temp-101',
  })
  @IsOptional()
  @IsString()
  tempId?: string;
}

export class OfflineOrderEntry {
  @ApiProperty({
    description: 'Listing identifier, either a real DB UUID or a temporary offline-listing-temp ID from this batch',
    example: 'offline-listing-temp-101',
  })
  @IsNotEmpty()
  @IsString()
  tempListingId: string;

  @ApiProperty({
    description: 'Quantity of items ordered',
    example: 10,
  })
  @IsNotEmpty()
  @IsNumber()
  quantity: number;

  @ApiProperty({
    description: 'Unique client-side tracking key to verify idempotency',
    example: 'sync-uuid-99238',
  })
  @IsNotEmpty()
  @IsString()
  syncId: string;
}

export class SyncOfflineDto {
  @ApiProperty({
    description: 'Listings drafted offline that need to be published',
    type: [OfflineListingEntry],
  })
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => OfflineListingEntry)
  listings: OfflineListingEntry[];

  @ApiProperty({
    description: 'Order transactions queued offline',
    type: [OfflineOrderEntry],
  })
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => OfflineOrderEntry)
  orders: OfflineOrderEntry[];
}
