import { Controller, Post, Get, Body, Query, UseGuards } from '@nestjs/common';
import { ApiTags, ApiOperation, ApiResponse, ApiBearerAuth, ApiQuery } from '@nestjs/swagger';
import { ExportService } from './export.service';
import { CreateDocumentDto } from './dto/create-document.dto';
import { JwtAuthGuard } from '../../common/guards/jwt-auth.guard';
import { RolesGuard } from '../../common/guards/roles.guard';
import { Roles } from '../../common/decorators/roles.decorator';
import { User, UserRole } from '@prisma/client';
import { CurrentUser } from '../../common/decorators/current-user.decorator';

@ApiTags('Export Regulatory Assistant')
@ApiBearerAuth()
@UseGuards(JwtAuthGuard)
@Controller('export')
export class ExportController {
  constructor(private readonly exportService: ExportService) {}

  @Post('documents')
  @UseGuards(RolesGuard)
  @Roles(UserRole.EXPORTER, UserRole.ADMIN)
  @ApiOperation({
    summary: 'Automate regulatory export document generation',
    description: 'Generates trade-compliance documents (e.g. Phytosanitary, Origin Certs) mapped against export templates. Restricted to Exporters and Admins.',
  })
  @ApiResponse({ status: 201, description: 'Export document generated and saved.' })
  @ApiResponse({ status: 401, description: 'Unauthorized JWT.' })
  @ApiResponse({ status: 403, description: 'Forbidden.' })
  async createDoc(@CurrentUser() user: User, @Body() dto: CreateDocumentDto) {
    return this.exportService.createDocument(user.id, dto);
  }

  @Get('documents')
  @UseGuards(RolesGuard)
  @Roles(UserRole.EXPORTER, UserRole.ADMIN)
  @ApiOperation({
    summary: 'Retrieve all submitted export documents',
    description: 'Lists all regulatory compliance forms generated by the authenticated exporter.',
  })
  @ApiResponse({ status: 200, description: 'Documents list loaded successfully.' })
  @ApiResponse({ status: 401, description: 'Unauthorized.' })
  async getDocs(@CurrentUser() user: User) {
    return this.exportService.getDocuments(user.id);
  }

  @Get('customs-checklist')
  @ApiOperation({
    summary: 'Get customs compliance checklist and tariff indicator',
    description: 'Provides regulatory checklists, quarantine directives (NAQS/NEPC), average transit durations, and tariff rates for exporting agricultural products to target countries (e.g. USA, UK, Netherlands).',
  })
  @ApiQuery({ name: 'destinationCountry', required: true, description: 'Target export country (e.g. USA, Netherlands)', example: 'USA' })
  @ApiQuery({ name: 'commodity', required: true, description: 'Agricultural commodity name (e.g. Ginger, Cocoa Beans)', example: 'Ginger' })
  @ApiResponse({ status: 200, description: 'Customs checklist and tariff rates retrieved successfully.' })
  @ApiResponse({ status: 401, description: 'Unauthorized.' })
  async getChecklist(
    @Query('destinationCountry') destination: string,
    @Query('commodity') commodity: string,
  ) {
    return this.exportService.getCustomsChecklist(destination, commodity);
  }
}
